[tool.poetry]
name = "simple-excel-etl"
version = "0.1.0"
description = ""
authors = ["Philip Martins <philip.martt@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
